boldapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from bold import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_user, name='logout'),
    url(r'^tableau/', views.tableau, name='tableau'),
    url(r'^prediction/', views.prediction, name='prediction'),
    url(r'^experiment/', views.experiment, name='experiment'),
    url(r'^matchbox/', views.matchbox, name='matchbox'),
    url(r'^matchboxhandler/', views.matchbox_handler, name='matchbox_handler'),
]

bold/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

bold/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms


choices = (
    ('15', 'Brigham Young University Food'), ('29', 'Texas Roadhouse'), ('418', 'BYU Legends Grille'), ('437', 'Brick Oven Provo'), ('516', 'The Wall - BYU'),
    ('693', 'Papa John\'s Pizza'), ('1365', 'Mountain West Burrito'), ('1401', 'Burgers Supreme'), ('1445', 'Chen\'s Noodle House'), ('374', 'Commons At The Cannon Center'),
    ('638', 'Panda Express'), ('695', 'NrGize'), ('4816', 'The Awful Waffle')
)

genders = (
    ('0', 'Female'), ('1', 'Male')
)

carriers = (
    ('Verizon', 'Verizon'), ('AT&T', 'AT&T'), ('Sprint', 'Sprint'), ('T-Mobile', 'T-Mobile')
)

users = (
    ('161', '161'), ('252', '252'), ('258', '258'), ('264', '264'), ('278', '278'), ('281', '281'), ('284', '284'), ('301', '301'), ('315', '315'), ('324', '324'),
)



class GenderPredictionForm(ModelForm):
    facebook = forms.BooleanField(initial=False, required=False)
    pinterest = forms.BooleanField(initial=False, required=False)
    pandora = forms.BooleanField(initial=False, required=False)
    espn = forms.BooleanField(initial=False, required=False, label='ESPN')
    linkedin = forms.BooleanField(initial=False, required=False)

    class Meta:
        model = User
        fields = ['facebook', 'pinterest', 'linkedin', 'pandora', 'espn']





class MatchboxForm(ModelForm):

    user_id = forms.ChoiceField(choices=users, required=False, label='User ID', help_text='Please select your User ID')
    facebook = forms.BooleanField(initial=False, required=False)
    instagram = forms.BooleanField(initial=False, required=False)
    drawsomething = forms.BooleanField(initial=False, required=False)
    templerun = forms.BooleanField(initial=False, required=False)
    clashofclans = forms.BooleanField(initial=False, required=False, label='Clash of Clans')
    wwffree = forms.BooleanField(initial=False, required=False, label='Words With Friends')
    pinterest = forms.BooleanField(initial=False, required=False)
    pandora = forms.BooleanField(initial=False, required=False)
    espn = forms.BooleanField(initial=False, required=False, label='ESPN')
    linkedin = forms.BooleanField(initial=False, required=False)
    twitter = forms.BooleanField(initial=False, required=False)
    netflix = forms.BooleanField(initial=False, required=False)
    groupon = forms.BooleanField(initial=False, required=False)
    newyorktimes = forms.BooleanField(initial=False, required=False, label='New York Times')
    gender = forms.ChoiceField(choices=genders, required=False, label='Gender')
    carrier = forms.ChoiceField(choices=carriers, required=False, label='Carrier')

    restaurant = forms.ChoiceField(choices=choices, required=False, label='Restaurant')
    visits = forms.IntegerField(min_value=0, label='Number of visits during the semester:')


    class Meta:
        model = User
        fields = [ 'facebook','instagram', 'drawsomething','templerun', 'clashofclans','wwffree', 'pinterest','pandora', 'linkedin','twitter', 'netflix', 'groupon', 'newyorktimes', 'espn','user_id', 'gender','carrier', 'restaurant', 'visits']

bold/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.models import User
# from project3.models import User, Equipment, Department, Manufacturer
# from project3.forms import UserForm, EquipmentForm, DepartmentForm, ManufacturerForm
# import urllib2
# from urllib.request import urlopen, Request
import urllib
import urllib3
import json
# import requests
import codecs
import decimal
from bold.forms import GenderPredictionForm, MatchboxForm

from django.contrib import messages


def login_view(request):
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect('/')
            else:
                messages.error(request, 'Please contact your administrator to activate your account.')
        else:
            messages.error(request, 'Login is invalid.')
    context_dict = {'request': request}
    return render(request, 'login.html', context_dict)


def logout_user(request):
    logout(request)
    return render(request, "login.html")


@login_required(login_url='/login/')
def index(request):
    context_dict = {'request': request}
    return render(request, "home.html", context_dict)


@login_required(login_url='/login/')
def tableau(request):
    context_dict = {'request': request}
    return render(request, "tableau.html", context_dict)

@login_required(login_url='/login/')
def prediction(request):

    genderform = GenderPredictionForm()

    context_dict = {'request': request, 'genderform': genderform}
    return render(request, "prediction.html", context_dict)


def experiment(request):

    facebook = request.GET.get('facebook', None)
    pinterest = request.GET.get('pinterest', None)
    pandora = request.GET.get('pandora', None)
    espn = request.GET.get('espn', None)
    linkedin = request.GET.get('linkedin', None)

    facebook = str(facebook)
    pintrest = str(pinterest)
    pandora = str(pandora)
    espn = str(espn)
    linkedin = str(linkedin)
    test = "1"

    data = {

        "Inputs": {

            "input1":
                {
                    "ColumnNames": ["user_id", "facebook", "instagram", "drawsomething", "templerun", "clashofclans",
                                    "wwffree", "pinterest", "pandora", "espn", "linkedin", "twitter", "netflix",
                                    "groupon", "newyorktimes", "gender", "carrier"],
                    "Values": [
                        ["0", facebook, "0", "0", "0", "0", "0", pinterest, pandora, espn, linkedin, "0", "0", "0", "0", "0", "value"],
                        ["0", facebook, "0", "0", "0", "0", "0", pinterest, pandora, espn, linkedin, "0", "0", "0", "0", "0", "value"], ]
                }, },
        "GlobalParameters": {
        }
    }

    body = str.encode(json.dumps(data))

    url = 'https://ussouthcentral.services.azureml.net/workspaces/82e21ff375ba4d35800059164b8a2e64/services/3dd5dad3429b4f52bf9035936a87c75b/execute?api-version=2.0&details=true'
    api_key = 'qfWmNpQ6lyTFQ1ZLEbRgCaXnXKhXToVkEWDVfmu1NkJsG+xHj0x0yBvbhQxjrqacw7NOMuJUcEgDG7eD2XrjNg=='  # Replace this with the API key for the web service
    headers = {'Content-Type': 'application/json', 'Authorization': ('Bearer ' + api_key)}


    # req = urllib.request.Request(url, body, headers)



    http = urllib3.PoolManager()



    r = http.request('POST', url, body=body, headers=headers)

    # body = r.data.read().decode('utf-8')

    testresult = json.loads(str(r.data,'utf-8'))

    # try:
    #     with open(r.data['Results']['output1']['value']['Values']) as test:
    #         testresult = json.load(test)
    # except Exception as e:
    #     print(e)
    # print(testresult)
    output = testresult['Results']['output1']['value']['Values'][0][7]


    prediction  = ''
    output = decimal.Decimal(output)
    if output >= .5:
        prediction = 'Male'
    else:
        prediction = 'Female'
    # print(output)


    # print(testresult)



    return JsonResponse({'result': prediction})


@login_required(login_url='/login/')
def matchbox(request):

    matchboxform = MatchboxForm()

    context_dict = {'request': request, 'genderform': matchboxform}
    return render(request, "matchbox.html", context_dict)


def matchbox_handler(request):

    name = request.GET.get('name', None)
    location_id = request.GET.get('location_id', None)
    visit_count = request.GET.get('visit_count', None)


    facebook = request.GET.get('facebook', None)
    instagram = request.GET.get('instagram', None)
    drawsomething = request.GET.get('drawsomething', None)
    templerun = request.GET.get('templerun', None)
    clashofclans = request.GET.get('clashofclans', None)
    wwffree = request.GET.get('wwffree', None)
    pinterest = request.GET.get('pinterest', None)
    pandora = request.GET.get('pandora', None)
    linkedin = request.GET.get('linkedin', None)
    twitter = request.GET.get('twitter', None)
    netflix = request.GET.get('netflix', None)
    groupon = request.GET.get('groupon', None)
    newyorktimes = request.GET.get('newyorktimes', None)
    espn = request.GET.get('espn', None)
    user_id = request.GET.get('user_id', None)
    gender = request.GET.get('gender', None)
    carrier = request.GET.get('carrier', None)




    name = str(name)
    location_id = str(location_id)
    visit_count = str(visit_count)
    facebook = str(facebook)
    instagram = str(instagram)
    drawsomething= str(drawsomething)
    templerun= str(templerun)
    clashofclans= str(clashofclans)
    wwffree= str(wwffree)
    pinterest= str(pinterest)
    pandora= str(pandora)
    linkedin= str(linkedin)
    twitter= str(twitter)
    netflix= str(netflix)
    groupon= str(groupon)
    newyorktimes= str(newyorktimes)
    espn= str(espn)
    user_id= str(user_id)
    gender= str(gender)
    carrier= str(carrier)

    data = {

        "Inputs": {

            "input2":
                {
                    "ColumnNames": ["user_id", "facebook", "instagram", "drawsomething", "templerun", "clashofclans",
                                    "wwffree", "pinterest", "pandora", "espn", "linkedin", "twitter", "netflix",
                                    "groupon", "newyorktimes", "gender", "carrier"],
                    "Values": [
                        [user_id, facebook, instagram, drawsomething, templerun, clashofclans, wwffree, pinterest, pandora, espn, linkedin, twitter, netflix, groupon, newyorktimes, gender, carrier],
                        ]
                },
            "input1":
                {
                    "ColumnNames": ["user_id", "name", "location_id", "visit_count", "Visit_count Log"],
                    "Values": [[user_id, name, location_id, visit_count, "0"], ]
                }, },
        "GlobalParameters": {
        }
    }

    body = str.encode(json.dumps(data))

    url = 'https://ussouthcentral.services.azureml.net/workspaces/82e21ff375ba4d35800059164b8a2e64/services/46942248d9094ef1b3320bcd26de9952/execute?api-version=2.0&details=true'
    api_key = '1VZd2B/4od8He86jXaZkHjv0JPdxt1FrmrzchxskjP+5bW8tIVnBraTkeXdHCpTnrVz1Hoc0d8/GdHyO7CX5rQ=='  # Replace this with the API key for the web service
    headers = {'Content-Type': 'application/json', 'Authorization': ('Bearer ' + api_key)}
    # req = urllib2.Request(url, body, headers)

    http = urllib3.PoolManager()

    r = http.request('POST', url, body=body, headers=headers)

    testresult = json.loads(str(r.data,'utf-8'))

    output1 = testresult['Results']['output1']['value']['Values'][0][1]
    output2 = testresult['Results']['output1']['value']['Values'][0][2]
    output3 = testresult['Results']['output1']['value']['Values'][0][3]


    output1 = str(output1)
    output2 = str(output2)
    output3 = str(output3)

    if output1 == '4457':
        output1 = 'Golden Resaurant'
    if output2 == '516':
        output2 = 'The Wall'
    if output3 == '1119':
        output3 = 'Riverside Country Club'


    return JsonResponse({'output1': output1, 'output2': output2, 'output3': output3})

bold/templates/home.html
{% extends "main.html" %}
{% block pageheader %}
   Home Page
{% endblock %}
{% block breadcrumbs %}
   <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
{% endblock %}

{% block content %}
    <div class="box">
        <div class="box-header">

        </div>
        <div class="box-body">


    <div class="col-lg-12">
            <h2>IS 415 - Capstone Project</h2>

            <h4>Andrew Wiser, Greggory Peck, Misha Milovidov, and Shaun Quinton</h4>

    </div>
    </div>
     </div>
{% endblock %}

{% block scriptblock %}
{% endblock %}

bold/templates/login.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static "AdminLTE/bootstrap/css/bootstrap.min.css" %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "AdminLTE/dist/css/AdminLTE.min.css" %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "AdminLTE/plugins/iCheck/square/blue.css" %}">
    <link rel="stylesheet" href="{% static "AdminLTE/dist/css/skins/skin-rmi.css" %}">
    <link rel="stylesheet" href="{% static "css/pathfinder.css" %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
{#    <img style="max-width:350px" src="{% static "img/pathbanner.png" %}" />#}
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
                  {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ message }}
                  </div>
        {% endfor %}
        {% endif %}

    <form action="/login/" method="post" id="login-form">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="input" class="form-control" placeholder="Email" id="username" name="username">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" id="password" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>

{#        <p>User: admin Password: password</p>#}
      <div class="row">
        <div class="col-xs-8">
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-warning btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="{% static "AdminLTE/plugins/jQuery/jquery-2.2.3.min.js" %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static "AdminLTE/bootstrap/js/bootstrap.min.js" %}"></script>
<!-- iCheck -->
<script src="{% static "AdminLTE/plugins/iCheck/icheck.min.js" %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>

bold/templates/matchbox.html
{% extends "main.html" %}
{% load static %}
{% block pageheader %}
   Matchbox Calculator
{% endblock %}
{% block breadcrumbs %}

{% endblock %}

{% block content %}
    <div class="box">
        <div class="box-header">
            <h2>Matchbox prediction by applications installed.</h2>

            <h4>Select any applications that have been installed on your smartphone.</h4>
        </div>
        <div class="box-body">


    <div class="col-lg-12">
    <br>

            {% load widget_tweaks %}
            {% for field in genderform %}
                <div class="form-group col-md-6">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% if field|widget_type != 'checkboxinput' %}
                        {{ field|append_attr:"class:form-control" }}
                        {{ field.default_error_messages }}
                        {% else %}
                            {{ field }}
                            {{ field.default_error_messages }}
                    {% endif %}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
    </div>
        <div class="box-footer">
            <div>
                <button class="btn btn-warning col-md-12" value="" onclick="getPrediction()">Predict</button>
            </div>
            <br>
            <br>
            <hr>
            <div class="col-md-12 text-center">
                <h4>Prediction Result 1: <span id="output1"></span></h4>
                <h4>Prediction Result 2: <span id="output2"></span></h4>
                <h4>Prediction Result 3: <span id="output3"></span></h4>
            </div>

        </div>




        <div class="col-lg-6">



        </div>
    </div>
     </div>
{% endblock %}

{% block scriptblock %}

     <script src="{% static 'js/asynchandler.js' %}"></script>

    <script type="text/javascript">


    var Globals = {
        csrfmiddlewaretoken: '{{ csrf_token }}'

    };

    function getPrediction()
        {


            // $loading = $('.fixed-table-loading');
            // $loading.html('<div style="background-color: #ffffff"><h2><i class="fa fa-refresh fa-spin" aria-hidden="true"></i></h2>Loading Items, please wait..</div>');
            // $loading.show();
            //var utl = (?P<projectid>\d+)/project/paymentapp/(?P<itemid>\d+)/paymentappitems/


            var facebook = 0;
            var instagram = 0;
            var drawsomething = 0;
            var templerun = 0;
            var clashofclans = 0;
            var wwffree = 0;
            var pinterest = 0;
            var pandora = 0;
            var linkedin = 0;
            var twitter = 0;
            var netflix = 0;

            var groupon = 0;
            var newyorktimes = 0;
            var espn = 0;



            if($("#id_facebook").is(':checked')){
                facebook = 1;
            }
            if($("#id_instagram").is(':checked')){
                instagram = 1;
            }
            if($("#id_drawsomething").is(':checked')){
                drawsomething = 1;
            }
            if($("#id_templerun").is(':checked')){
                templerun = 1;
            }
            if($("#id_clashofclans").is(':checked')){
                clashofclans = 1;
            }
            if($("#id_wwffree").is(':checked')){
                wwffree = 1;
            }
            if($("#id_pinterest").is(':checked')){
                pinterest = 1;
            }
            if($("#id_pandora").is(':checked')){
                pandora = 1;
            }
            if($("#id_linkedin").is(':checked')){
                linkedin = 1;
            }
            if($("#id_twitter").is(':checked')){
                twitter = 1;
            }
            if($("#id_netflix").is(':checked')){
                netflix = 1;
            }
            if($("#id_groupon").is(':checked')){
               groupon  = 1;
            }
            if($("#id_newyorktimes").is(':checked')){
                newyorktimes = 1;
            }
            if($("#id_espn").is(':checked')){
                espn = 1;
            }




             var name = $('#id_restaurant option:selected').text();
             var location_id = $('#id_restaurant').val();
             var visit_count = $('#id_visits').val();
            var user_id = $('#id_user_id').val();
            var gender = $('#id_gender').val();
            var carrier = $('#id_carrier').val();




            var url = '/matchboxhandler/';
            var data = {
                csrfmiddlewaretoken: Globals.csrfmiddlewaretoken,
                name: name,
                location_id: location_id,
                visit_count: visit_count,
                facebook: facebook,
                instagram: instagram,
                drawsomething :drawsomething,
                templerun :templerun,
                clashofclans :clashofclans,
                wwffree :wwffree,
                pinterest :pinterest,
                pandora :pandora,
                linkedin :linkedin,
                twitter :twitter,
                netflix :netflix,
                groupon :groupon,
                newyorktimes :newyorktimes,
                espn :espn,
                user_id: user_id,
                gender: gender,
                carrier: carrier

        };




            GetData('GET',url,data,predictionReturn);
        }


    function predictionReturn(data){
        var output1 = data.output1;
        var output2 = data.output2;
        var output3 = data.output3;

        $('#output1').text(output1);
        $('#output2').text(output2);
        $('#output3').text(output3);

    }


    </script>

{% endblock %}

bold/templates/prediction.html
{% extends "main.html" %}
{% load static %}
{% block pageheader %}
   Prediction Calculator
{% endblock %}
{% block breadcrumbs %}

{% endblock %}

{% block content %}
    <div class="box">
        <div class="box-header">
            <h2>Gender prediction by applications installed.</h2>

            <h4>Select the applications currently installed on your smartphone.</h4>
        </div>
        <div class="box-body">


    <div class="col-lg-6">

            {% load widget_tweaks %}
            {% for field in genderform %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% if field|widget_type != 'checkboxinput' %}
                        {{ field|append_attr:"class:form-control" }}
                        {{ field.default_error_messages }}
                        {% else %}
                            {{ field }}
                            {{ field.default_error_messages }}
                    {% endif %}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <button class="btn btn-warning col-md-2" value="" onclick="getPrediction()">Predict</button>

    </div>

        <div class="col-lg-6">
            <h4>Prediction Results: <span id="results"></span></h4>


        </div>
    </div>
     </div>
{% endblock %}

{% block scriptblock %}

     <script src="{% static 'js/asynchandler.js' %}"></script>

    <script type="text/javascript">


    var Globals = {
        csrfmiddlewaretoken: '{{ csrf_token }}'

    };

    function getPrediction()
        {

            // $loading = $('.fixed-table-loading');
            // $loading.html('<div style="background-color: #ffffff"><h2><i class="fa fa-refresh fa-spin" aria-hidden="true"></i></h2>Loading Items, please wait..</div>');
            // $loading.show();
            //var utl = (?P<projectid>\d+)/project/paymentapp/(?P<itemid>\d+)/paymentappitems/
            var facebook = 0;
            var pinterest = 0;
            var linkedin = 0;
            var pandora = 0;
            var espn = 0;


            if($("#id_facebook").is(':checked')){
                facebook = 1;
            }
            if($("#id_pinterest").is(':checked')){
                pinterest = 1;
            }
            if($("#id_linkedin").is(':checked')){
                linkedin = 1;
            }
            if($("#id_pandora").is(':checked')){
                pandora = 1;
            }
            if($("#id_espn").is(':checked')){
                espn = 1;
            }




            var url = '/experiment/';
            var data = { csrfmiddlewaretoken:Globals.csrfmiddlewaretoken, facebook : facebook, pinterest : pinterest, linkedin : linkedin, pandora : pandora, espn : espn};
            GetData('GET',url,data,predictionReturn);
        }


    function predictionReturn(data){
        var result = data.result;
        $('#results').text(result);

    }


    </script>

{% endblock %}

bold/templates/sidebar.html
    <ul class="sidebar-menu">
            <li{% if '/' == request.path %} class="active" {% endif %}><a href="/"><i class="fa fa-home"></i> <span>Home Page</span></a></li>
            <li{% if '/matchbox/' in request.path %} class="active" {% endif %}><a href="/matchbox/"><i class="fa fa-th"></i> <span>Matchbox</span></a></li>
            <li{% if '/prediction/' in request.path %} class="active" {% endif %}><a href="/prediction/"><i class="fa fa-flask"></i> <span>Prediction</span></a></li>
            <li{% if '/tableau/' in request.path %} class="active" {% endif %}><a href="/tableau/"><i class="fa fa-bar-chart"></i> <span>Tableau</span></a></li>
          </ul>

bold/templates/tableau.html
{% extends "main.html" %}
{% block pageheader %}
  Tableau
{% endblock %}
{% block styleblock %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <script type="text/javascript" src="//public.tableau.com/javascripts/api/tableau-2.min.js"></script>
        <script type="text/javascript">

{#        $vizbody = $('#vizbody');#}

     var viz, workbook, activeSheet;

            function initViz() {
                var containerDiv = document.getElementById("vizContainer"),
                url = "https://public.tableau.com/views/Appeatingpreferences/Sheet1?:embed=y&:display_count=yes&publish=yes";
                var options = {

                    hideTabs: true,
                    hideToolbar: true,
                    onFirstInteractive: function () {
                    workbook = viz.getWorkbook();
                    activeSheet = workbook.getActiveSheet();
                    }
                };
                viz = new tableau.Viz(containerDiv, url, options);
            }


{#            function filterOnValue() {#}
{#                console.log('in the function');#}
{#                  activeSheet.applyFilterAsync(#}
{#                    "Name",#}
{#                    ["Mcdonald's", "Taco Bell", "Panda Express"],#}
{##}
{#                    tableau.FilterUpdateType.REPLACE);#}
{#                }#}


                function filterOnValue() {
                console.log('here');
                    var filtervalue = $('#restraunt_select').val();
                    activeSheet = workbook.getActiveSheet();

                    if (filtervalue !== '#') {
                        activeSheet.applyFilterAsync(
                        "Name",
                        filtervalue,
                        tableau.FilterUpdateType.REPLACE);
                    }

                }

                function clearFilters() {
                  workbook.revertAllAsync();
                }


                function clearSelection() {
                    workbook.getActiveSheet().clearSelectedMarksAsync();
                }








                function sheetChange() {
                    if($('#sheet_select').val() === 'restaurants'){
                        workbook.activateSheetAsync("Sheet 1");
                        $('#footer').show();
                    }



                    else if ($('#sheet_select').val() === 'gender'){
                          workbook.activateSheetAsync("Sheet 2");
                          $('#footer').hide();
                    }

                }





    </script>

{% endblock %}
{% block breadcrumbs %}

{% endblock %}

{% block content %}
    <div class="box">
        <div class="box-header">

            <select class="form-control col-md-3" id="sheet_select" onchange="sheetChange()">
                    <option value="restaurants">Apps and Restaurants</option>
                    <option value="gender">Apps and Gender</option>

                </select>

        </div>
        <div class="box-body">
            <div id="vizbody">



            <div id="vizContainer"></div>

            </div>
            <div class="box-footer" id="footer">
                <hr>

                <div class="col-md-5">
                <select class="form-control col-md-3" id="restraunt_select">
                    <option value="#">Select a Restraunt</option>
                    <option value="Panda Express">Panda Express</option>
                    <option value="Mountain West Burrito">Mountain West Burrito</option>
                    <option value="SUBWAY">Subway</option>
                    <option value="J Dawgs">J Dawgs</option>
                    <option value="MOA Cafe">MOA Cafe</option>
                </select>
                </div>
                <button class="btn btn-warning col-md-2" onclick="filterOnValue()" value="Filter on Restraunt">Filter on Restraunt</button>
{#                <input class="btn btn-warning" onclick="clearSelection()" value="Clear">#}
                <div>
                    <button class="btn btn-danger" onclick="clearFilters()" value="Clear Selections" style="float: right;">Clear Selections</button>
                </div>
            </div>


    </div>
    </div>
     </div>
{% endblock %}

{% block scriptblock %}

    <script>

$(document).ready(function() {
  initViz();
});
    </script>

{% endblock %}